export const institution = [
  'BUET',
  'CUET',
  'KUET',
  'RUET',
  'DU',
  'CU',
  'RU',
  'KU',
  'JU',
  'JnU',
  'SUST',
  'JUST',
  'PUST',
  'NUST',
];

// "Agricultural and Biological Science",
// "Biochemistry", "Molecular and Cell Biology",
// "Veterinary",
// "Arts and Humanities",
// "Social Science", "Psychology", "Education",
// "Business", "Management and Accounting",
// "Economics", "Econometrics and Finance",
// "Mathematics",
// "Physics", "Astronomy", "Energy",
// "Chemistry", "Chemical Engine`ering",
// "Computer Science", "Decision Science", "ICT", "IT",
// "EEE", "ETE", "ECE", "Energy", "Material Science",
// "Environmental Science"
// "Health Science", "Medicine", "Dentistry", "Health", "Professions", "Nursing",
// "Neuroscience",
// "Pharmacology", "Toxicology and Pharmaceutics",
// "Food Science and Nutrition"
// Engineering and Technology
// **Ref:

export const occupation = [
  'Teacher',
  'Under Grad Student',
  'Post Grad Student',
];


export const researchField = [
  'Agricultural and Biological Science',
  'Biochemistry',
  'Molecular and Cell Biology',
  'Veterinary',
  'Arts and Humanities',
  'Social Science',
  'Psychology',
  'Education',
  'Business',
  'Management and Accounting',
  'Economics',
  'Econometrics and Finance',
  'Mathematics',
  'Physics',
  'Astronomy',
  'Energy',
  'Chemistry',
  'Chemical Engineering',
  'Computer Science',
  'Decision Science',
  'ICT',
  'IT',
  'EEE',
  'ETE',
  'ECE',
  'Energy',
  'Material Science',
  'Environmental Science',
  'Health Science',
  'Medicine',
  'Dentistry',
  'Health',
  'Professions',
  'Nursing',
  'Neuroscience',
  'Pharmacology',
  'Toxicology and Pharmaceutics',
  'Food Science and Nutrition',
];
